=== Priyadharshini0101/flickpicker/Data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "integer" },
      "title": { "type": "string" },
      "dateWatched": { "type": "string", "format": "date" },
      "watched": { "type": "boolean" },
      "trailerLink": { "type": "string", "format": "uri" },
      "movieLink": { "type": "string", "format": "uri" },
      "modernTrailerLink": { "type": "string", "format": "uri" },
      "requestedBy": {
        "type": "object",
        "properties": {
          "userId": { "type": "string" },
          "username": { "type": "string" },
          "platform": { "type": "string" }
        },
        "required": ["userId", "username", "platform"]
      },
      "category": { "type": "string" },
      "trailerPrivate": { "type": "boolean" },
      "moviePrivate": { "type": "boolean" },
      "year": { "type": "integer", "minimum": 1888 },
      "subtitles": { "type": "boolean" },
      "language": { "type": "string" },
      "voteCount": { "type": "integer" },
      "imageUrl": { "type": "string", "format": "uri" },
      "runtime": { "type": "string" },
      "ratings": { "type": "string" }
    },
    "required": ["id", "title", "watched", "trailerLink", "requestedBy", "year", "subtitles", "language", "voteCount", "imageUrl"]
  }
}

=== Priyadharshini0101/flickpicker/Data/movieList.json
[
    {
        "id": 1,
        "title": "A time machine",
        "dateWatched": "2022-01-01",
        "watched": false,
        "trailerLink": "https://youtu.be/sJzI6qSmJoQ",
        "movieLink": "https://youtu.be/movie-link-1",
        "modernTrailerLink": "https://youtu.be/modern-trailer-link-1",
        "requestedBy": {
            "userId": "987654320",
            "username": "gamer460",
            "platform": "Discord"
        },
        "category": "Action",
        "trailerPrivate": false,
        "moviePrivate": false,
        "year": 2017,
        "subtitles": true,
        "language": "en",
        "voteCount": 0,
        "imageUrl": "./img/movie1.jpg",
        "runtime": "1h37m",
        "ratings": "PG-13"
    },
    {
        "id": 2,
        "title": "Movie Title 2",
        "dateWatched": "2022-01-02",
        "watched": true,
        "trailerLink": "https://youtu.be/sJzI6qSmJoQ",
        "movieLink": "https://youtu.be/movie-link-2",
        "modernTrailerLink": "https://youtu.be/modern-trailer-link-2",
        "requestedBy": {
            "userId": "987654321",
            "username": "gamer461",
            "platform": "Twitch"
        },
        "category": "Comedy",
        "trailerPrivate": false,
        "moviePrivate": false,
        "year": 2018,
        "subtitles": true,
        "language": "en",
        "voteCount": 0,
        "imageUrl": "./img/movie1.jpg",
        "runtime": "1h37m",
        "ratings": "R"
    },
    {
        "id": 3,
        "title": "Movie Title 3",
        "dateWatched": "2022-01-03",
        "watched": true,
        "trailerLink": "https://youtu.be/sJzI6qSmJoQ",
        "movieLink": "https://youtu.be/movie-link-3",
        "modernTrailerLink": "https://youtu.be/modern-trailer-link-3",
        "requestedBy": {
            "userId": "987654322",
            "username": "gamer462",
            "platform": "Twitch"
        },
        "category": "Drama",
        "trailerPrivate": false,
        "moviePrivate": false,
        "year": 2019,
        "subtitles": true,
        "language": "en",
        "voteCount": 0,
        "imageUrl": "./img/movie1.jpg",
        "runtime": "1h37m",
        "ratings": "PG"
    },
    {
        "id": 4,
        "title": "Movie Title 4",
        "dateWatched": "2022-01-04",
        "watched": true,
        "trailerLink": "https://youtu.be/sJzI6qSmJoQ",
        "movieLink": "https://youtu.be/movie-link-4",
        "modernTrailerLink": "https://youtu.be/modern-trailer-link-4",
        "requestedBy": {
            "userId": "987654323",
            "username": "gamer463",
            "platform": "Twitch"
        },
        "category": "Thriller",
        "trailerPrivate": false,
        "moviePrivate": false,
        "year": 2020,
        "subtitles": true,
        "language": "en",
        "voteCount": 0,
        "imageUrl": "./img/movie1.jpg",
        "runtime": "1h37m",
        "ratings": "R"
    },
    {
        "id": 5,
        "title": "Movie Title 5",
        "dateWatched": "2022-01-05",
        "watched": true,
        "trailerLink": "https://youtu.be/sJzI6qSmJoQ",
        "movieLink": "https://youtu.be/movie-link-5",
        "modernTrailerLink": "https://youtu.be/modern-trailer-link-5",
        "requestedBy": {
            "userId": "987654324",
            "username": "gamer464",
            "platform": "Twitch"
        },
        "category": "Horror",
        "trailerPrivate": false,
        "moviePrivate": false,
        "year": 2021,
        "subtitles": true,
        "language": "en",
        "voteCount": 0,
        "imageUrl": "./img/movie1.jpg",
        "runtime": "1h37m",
        "ratings": "NC-17"
    },
    {
        "id": 6,
        "title": "Movie Title 6",
        "dateWatched": "2022-01-06",
        "watched": true,
        "trailerLink": "https://youtu.be/sJzI6qSmJoQ",
        "movieLink": "https://youtu.be/movie-link-6",
        "modernTrailerLink": "https://youtu.be/modern-trailer-link-6",
        "requestedBy": {
            "userId": "987654325",
            "username": "gamer465",
            "platform": "Twitch"
        },
        "category": "Action",
        "trailerPrivate": false,
        "moviePrivate": false,
        "year": 2017,
        "subtitles": true,
        "language": "en",
        "voteCount": 0,
        "imageUrl": "./img/movie1.jpg",
        "runtime": "1h37m",
        "ratings": "PG-13"
    }
]
